name: Container Build
description: コンテナイメージをビルドし、ECRへプッシュします。
inputs:
  ecr-repository-uri:
    required: true
    description: ECRリポジトリのURI
  dockerfile-path:
    required: true
    description: Dockerfileのパス
outputs:
  container-image:
    value: ${{ steps.meta.outputs.tags }}
    description: ビルドしたコンテナイメージ
runs:
  using: composite
  steps:
    - uses: aws-actions/amazon-ecr-login@v2 # Amazon ECRへのログイン
    - id: create
      # GitHub Appsトークンの生成
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        repositories: ${{ env.TARGET_REPO }}
    - name: Set up GitHub App token for Go module access
      run: |
        git config --global url."https://x-access-token:${{ steps.create.outputs.token }}@github.com/".insteadOf "https://github.com/"
        echo "GOPRIVATE=github.com/${{ github.repository_owner }}" >> $GITHUB_ENV
      shell: bash
    - name: Pre-fetch Go modules
      run: |
        cd .
        go mod download
      shell: bash
    - uses: docker/metadata-action@v5
      # コンテナイメージのメタデータ生成
      id: meta
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: type=sha,format=long
    - uses: docker/build-push-action@v5
      # コンテナイメージのビルドとプッシュ
      with:
        push: true
        context: ${{ inputs.dockerfile-path }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
