name: OpenID Connect
on: push
env:
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
  # SESSION_NAMEは後続stepで生成
jobs:
  connect:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Set safe session name
        # リポジトリ名を取得し、許可されていない文字をハイフンに置換
        run: |
          repo="${GITHUB_REPOSITORY#*/}"
          safe_repo=$(echo "$repo" | sed 's/[^a-zA-Z0-9+=,.@-]/-/g')
          echo "SESSION_NAME=${safe_repo}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ap-northeast-1
        env:
          SESSION_NAME: ${{ env.SESSION_NAME }}
      - run: aws iam list-users # 一時クレデンシャルの利用
      - run: aws iam create-user --user-name invalid || true
